DELETE http://localhost:3003/api/blogs/63175752a4703888f7ab5168
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMTc0NGVlZGM1ZGU5YTAxMjA2NDNjZSIsImlhdCI6MTY2MjQ3MzM1Mn0.JtcdS8lMB0RxfAf0_yv0GQBEO0JgL46No8t2EXnmyjQ